services:
  webtop:
    image: gitzjoey/webtop:latest
    container_name: webtop
    hostname: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/
      - TITLE=WebTop
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=git|nodejs
      - CUSTOM_USER=gitzjoey
      - PASSWORD=gitzjoey_webtop
    volumes:
      - /home/gitzjoey/webtop:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3440:3000
      - 3441:3001
    shm_size: "1gb"
    restart: no
