services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - '8585:8080'
    volumes:
      - /root/StirlingPDF/trainingData:/usr/share/tessdata
      - /root/StirlingPDF/extraConfigs:/configs
      - /root/StirlingPDF/customFiles:/customFiles/
      - /root/StirlingPDF/logs:/logs/
      - /root/StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
