services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: AnythingLLM
    ports:
      - "4000:3001"
    cap_add:
      - SYS_ADMIN
    volumes:
      - anythingllm_data:/app/server/storage
    environment:
      - STORAGE_DIR=/app/server/storage
      - LLM_PROVIDER=perplexity
      - PERPLEXITY_API_KEY=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
      - VECTOR_DB=lancedb
      - PASSWORDMINCHAR=8
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
    restart: no

volumes:
  anythingllm_data:
