services:
  vscode:
    image: gitzjoey/vscode:latest
    container_name: vscode
    hostname: vscode
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - SUBFOLDER=/
      - TITLE=VSCode Webtop
      - CUSTOM_USER=gitzjoey
      - PASSWORD=gitzjoey_vscode
    volumes:
      - /home/gitzjoey/vscode:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3610:3000
      - 3611:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: no
