services:
  opera:
    image: lscr.io/linuxserver/opera:latest
    container_name: opera
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - PASSWORD=gitzjoey_browse
      - CUSTOM_USER=gitzjoey
      - TITLE=Opera
    volumes:
      - opera_config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  opera_config:
