services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Singapore
    volumes:
      - /root/arrs/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: no

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Singapore
    volumes:
      - /root/arrs/lidarr/config:/config
      - /root/arrs/music:/music
      - /root/arrs/downloads:/downloads
    ports:
      - 8686:8686
    restart: no

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Singapore
      - TRANSMISSION_WEB_HOME=
      - USER=
      - PASS=
      - WHITELIST=
      - PEERPORT=
      - HOST_WHITELIST=
    volumes:
      - /root/arrs/transmission/data:/config
      - /root/arrs/downloads:/downloads
      - /root/arrs/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: no

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Singapore
    volumes:
      - /root/arrs/sonarr/config:/config
      - /root/arrs/tvseries:/tv
      - /root/arrs/downloads:/downloads
    ports:
      - 8989:8989
    restart: no

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Singapore
    volumes:
      - /root/arrs/radarr/config:/config
      - /root/arrs/movies:/movies
      - /root/arrs/downloads:/downloads
    ports:
      - 7878:7878
    restart: no
