services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/gitzjoey/lidarr/config:/config
      - /home/gitzjoey/music:/music
      - /home/gitzjoey/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
