services:
  kasmweb:
    image: gitzjoey/kasmweb:latest
    container_name: kasmweb
    hostname: kasmweb
    shm_size: "4gb"
    ports:
      - "6901:6901"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - kasmweb_home:/home/kasm-user
    restart: no
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined

volumes:
  kasmweb_home:
